version: 2
jobs:
  test:
    docker:
      - image: circleci/python:2
    working_directory: /home/circleci/gitstats
    steps:
      - checkout
      - run:
          name: deps
          command: sudo apt-get install gnuplot
      - run:
          name: test
          command: ./gitstats . html
      - store_artifacts:
          path: html

workflows:
  version: 2
  main:
    jobs:
      - test
